<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>usbpd_app_icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Python\.vscode\launch.json" />
    <Content Include="usbpd_app_icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Extended.Wpf.Toolkit" Version="5.0.0" />
    <PackageReference Include="ScottPlot.WPF" Version="5.1.58" />
    <PackageReference Include="System.IO.Ports" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Python\Environment\" />
  </ItemGroup>

</Project>
